# Generated by Django 3.0.5 on 2021-01-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_answercommentmentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmentions',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.PostComment'),
        ),
    ]
