# Generated by Django 3.1 on 2020-12-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_answercomment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answercomment',
            unique_together=set(),
        ),
    ]
