# Generated by Django 3.0.5 on 2021-01-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20210123_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercommentmentions',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.AnswerComment'),
        ),
    ]
