# Generated by Django 3.0.5 on 2021-01-24 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20210123_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentmentions',
            name='comment',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='mentions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='comment.PostCommentMentions'),
        ),
    ]
