# Generated by Django 3.0.5 on 2021-01-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210124_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='mentions',
        ),
        migrations.AddField(
            model_name='postcommentmentions',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.PostComment'),
        ),
    ]
