# Generated by Django 3.0.5 on 2021-01-24 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20210124_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmentions',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment_mentions', to='comment.PostComment'),
        ),
    ]
