# Generated by Django 3.0.5 on 2021-01-24 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_auto_20210124_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercommentmentions',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_comment_mentions', to='comment.AnswerComment'),
        ),
    ]
