# Generated by Django 3.0.5 on 2021-02-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.TextField(choices=[("{'subject': 'CS', 'color': '#7057ff'}", 'Cs'), ('STAT', 'Stat'), ('MATHEMATICS', 'Mathematics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('ZOOLOGY', 'Zoology'), ('BOTANY', 'Botany'), ('ES', 'Es'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
