# Generated by Django 3.1 on 2020-10-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
