# Generated by Django 3.0.5 on 2021-02-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210205_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hotness',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
