# Generated by Django 3.1 on 2020-10-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20201008_1323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
