# Generated by Django 3.1 on 2020-10-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_visitors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='PostVisitors',
        ),
    ]
