# Generated by Django 3.1 on 2020-10-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20201008_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='post',
        ),
    ]
