# Generated by Django 3.1 on 2020-10-08 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_visitors_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
    ]
