# Generated by Django 3.0.5 on 2021-02-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20210204_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='label',
        ),
    ]
