# Generated by Django 3.0.5 on 2021-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_remove_answer_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='up_vote_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
