# Generated by Django 3.1 on 2020-11-20 14:17

from django.db import migrations, models
import django.db.models.deletion
import taggit_suggest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('regex', models.CharField(help_text='Enter a valid Regular Expression. To make it case-insensitive include "(?i)" in your expression.', max_length=250, validators=[taggit_suggest.models.validate_regex])),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tregexes', to='taggit.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=30)),
                ('stem', models.CharField(max_length=30)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tkeywords', to='taggit.tag')),
            ],
        ),
    ]
