# Generated by Django 3.1 on 2020-10-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voteType',
            field=models.CharField(choices=[('EMPTY', 'Empty'), ('LIKE', 'Like'), ('DISLIKE', 'Dislike')], default='EMPTY', max_length=10),
        ),
    ]
