# Generated by Django 3.1 on 2020-10-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20201019_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='owner',
        ),
    ]
