# Generated by Django 3.1 on 2020-10-19 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0006_auto_20201019_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answervote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer.answer'),
        ),
        migrations.AlterField(
            model_name='answervote',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'owner')},
        ),
    ]
