# Generated by Django 3.1 on 2020-10-20 08:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answer', '0001_initial'),
        ('vote', '0009_auto_20201019_1641'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'owner')},
        ),
    ]
