# Generated by Django 3.1 on 2020-10-20 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_auto_20201008_2015'),
        ('vote', '0012_auto_20201020_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answervote',
            unique_together={('answer', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together={('post', 'owner')},
        ),
    ]
