# Generated by Django 3.1 on 2020-10-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20201020_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='postvote',
            name='post',
        ),
        migrations.DeleteModel(
            name='AnswerVote',
        ),
        migrations.DeleteModel(
            name='PostVote',
        ),
    ]
