# Generated by Django 3.1 on 2020-12-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_commentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
