# Generated by Django 3.1 on 2020-12-12 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0019_answercommentvote_postcommentvote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerCommentVote',
        ),
    ]
