# Generated by Django 3.1 on 2020-09-24 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutMe', models.TextField(blank=True, max_length=500)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastAccessDate', models.DateTimeField(auto_now=True)),
                ('profileImgUrl', models.URLField(null=True)),
                ('views', models.IntegerField(blank=True)),
                ('upVotes', models.IntegerField(blank=True)),
                ('downVotes', models.IntegerField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedIn', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
