# Generated by Django 3.1 on 2020-09-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImgUrl',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
