# Generated by Django 3.0.5 on 2021-02-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userinterests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_email_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
