# Generated by Django 3.1 on 2020-09-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200926_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
