# Generated by Django 3.1 on 2020-09-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20200924_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastAccessDate',
            field=models.DateTimeField(),
        ),
    ]
