# Generated by Django 3.1 on 2020-09-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20200927_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='downVotes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastAccessDate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileImgUrl',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upVotes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='views',
        ),
    ]
