# Generated by Django 3.1 on 2020-09-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20200927_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastAccessDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
