# Generated by Django 3.1 on 2020-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_profile_lastaccessdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileImgUrl',
            field=models.URLField(blank=True),
        ),
    ]
