# Generated by Django 3.1 on 2020-10-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profileImg',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileImgUrl',
        ),
    ]
