# Generated by Django 3.1 on 2020-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_auto_20201005_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
