# Generated by Django 3.1 on 2020-10-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_auto_20201005_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
