# Generated by Django 3.1 on 2020-10-07 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0030_auto_20201007_1130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
