# Generated by Django 3.1 on 2020-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0032_profile_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='downVotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='upVotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
