# Generated by Django 3.1 on 2020-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0034_auto_20201007_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='downVotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='upVotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
