# Generated by Django 3.1 on 2020-10-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0035_auto_20201007_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='displayName',
        ),
    ]
