# Generated by Django 3.1 on 2020-10-08 14:06

from django.db import migrations
import enumfields.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0036_remove_profile_displayname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userRole',
            field=enumfields.fields.EnumField(blank=True, default='USER', enum=user_profile.models.UserRole, max_length=10, null=True),
        ),
    ]
