# Generated by Django 3.1 on 2020-10-09 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0038_auto_20201009_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViewerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viwer_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viwer_user_agent_info', models.CharField(default='', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
