# Generated by Django 3.1 on 2020-10-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0039_profileviewerinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileviewerinfo',
            name='viewerUsername',
            field=models.TextField(blank=True, null=True),
        ),
    ]
