# Generated by Django 3.1 on 2020-10-09 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0040_profileviewerinfo_viewerusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileviewerinfo',
            name='profile',
        ),
        migrations.AddField(
            model_name='profileviewerinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileviewerinfo',
            name='visitDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Views',
        ),
    ]
