# Generated by Django 3.1 on 2020-10-09 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0041_auto_20201009_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('postViews', models.IntegerField(blank=True, null=True)),
                ('profileViews', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
