# Generated by Django 3.1 on 2020-10-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0042_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileviewerinfo',
            old_name='viwer_user_agent_info',
            new_name='viwer_agent_info',
        ),
        migrations.RenameField(
            model_name='profileviewerinfo',
            old_name='viwer_login_ip',
            new_name='viwer_ip',
        ),
    ]
