# Generated by Django 3.1 on 2020-11-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0045_auto_20201128_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
