# Generated by Django 3.1 on 2020-11-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0047_auto_20201128_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
