# Generated by Django 3.1 on 2020-11-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0048_auto_20201128_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
