# Generated by Django 3.1 on 2020-11-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0050_usercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontact',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_contact', serialize=False, to='user_profile.profile'),
        ),
    ]
