# Generated by Django 3.1 on 2020-11-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0053_auto_20201128_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserContact',
        ),
    ]
