# Generated by Django 3.1 on 2020-11-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0055_usercontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='credentials', serialize=False, to='auth.user')),
                ('employment', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('language', models.TextField(blank=True)),
            ],
        ),
    ]
