# Generated by Django 3.1 on 2020-11-28 16:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0056_usercredentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='language',
            field=django_mysql.models.ListCharField(models.CharField(max_length=30), max_length=186, size=6),
        ),
    ]
