# Generated by Django 3.1 on 2020-11-28 17:00

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0057_auto_20201128_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='language',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=30, null=True), blank=True, max_length=186, null=True, size=6),
        ),
    ]
