# Generated by Django 3.1 on 2020-11-29 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_profile', '0058_auto_20201128_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='education', serialize=False, to='auth.user')),
                ('school', models.TextField(blank=True)),
                ('degree', models.CharField(blank=True, max_length=10)),
                ('field_of_study', models.TextField(blank=True)),
                ('start_year', models.DateField(blank=True)),
                ('end_year', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEmployment',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employment', serialize=False, to='auth.user')),
                ('position', models.TextField(blank=True)),
                ('company', models.TextField(blank=True)),
                ('start_year', models.DateField(blank=True)),
                ('end_year', models.DateField(blank=True)),
                ('currently_work', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='language', serialize=False, to='auth.user')),
                ('language', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='skills', serialize=False, to='auth.user')),
                ('skill', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCredentials',
        ),
    ]
