# Generated by Django 3.1 on 2020-11-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0059_auto_20201129_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userlanguage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userskills',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEducation',
        ),
        migrations.DeleteModel(
            name='UserEmployment',
        ),
        migrations.DeleteModel(
            name='UserLanguage',
        ),
        migrations.DeleteModel(
            name='UserSkills',
        ),
    ]
