# Generated by Django 3.1 on 2020-11-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0061_usereducation_useremployment_userlanguage_userskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremployment',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremployment',
            name='start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
