# Generated by Django 3.1 on 2020-11-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0063_auto_20201129_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremployment',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useremployment',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
