# Generated by Django 3.1 on 2020-12-03 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0065_auto_20201130_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usereducation',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1969), django.core.validators.MaxValueValidator(2051)]),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='field_of_study',
            field=models.TextField(blank=True),
        ),
    ]
