# Generated by Django 3.0.5 on 2021-01-16 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Webinars',
            new_name='Webinar',
        ),
    ]
