# Generated by Django 3.0.5 on 2021-01-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinar',
            name='reference_url',
            field=models.URLField(null=True),
        ),
    ]
